#!/usr/bin/env python3
"""Discover the FinCEN advisory corpus into a manifest — AUTHORING-TIME ONLY.

Part of the Signal Watch ingestion pipeline (Phase 10 — SCALE). This widens the
hand-maintained 1-entry REGISTRY in acquire_fincen.py into a generated manifest of
the whole FinCEN advisories listing:

    crawl_fincen.py    → data/fincen/index.json   (manifest: {id,title,date,type,url})
    acquire_fincen.py  → data/fincen/raw/<id>.pdf (reads the manifest; resolves the PDF)
    pdf_to_md.py       → data/fincen/<id>.md      (verbatim source of truth)
    (hand-derive)      → config/typologies/<typology>.json
    build.py           → dist/<typology>/index.html

NON-NEGOTIABLE: nothing here ever runs in the ship artifact. The engine never
imports this; build.py stays stdlib-only and never fetches. This is a developer tool.

DETERMINISM SPLIT (so the committed manifest is reproducible without a live crawl):
  - parse_index(html) is a PURE function (HTML -> entries, no I/O). It is verified
    offline by `--selftest` against tests/fixtures/fincen-index.html, in the same
    runnable-stdlib-check spirit as build.py --check.
  - fetch_index() is a thin live shell (stdlib urllib, browser UA) used by `--fetch`
    to REFRESH the fixture. It is a manual authoring run, never in smoke/CI.
The committed data/fincen/index.json is generated by `--write` from the SAVED FIXTURE,
so it is reproducible offline.

The listing yields advisory DETAIL-PAGE urls (FinCEN PDF filenames are unpredictable);
resolving the actual PDF is an acquire-time hop (see acquire_fincen.py). FinCEN
advisories are U.S. federal works in the public domain (17 U.S.C. 105).

Usage:
    python3 scripts/crawl_fincen.py --selftest    # offline: parse the fixture + assert
    python3 scripts/crawl_fincen.py --write       # offline: fixture -> data/fincen/index.json
    python3 scripts/crawl_fincen.py --list        # offline: print parsed entries
    python3 scripts/crawl_fincen.py --fetch       # LIVE (manual authoring): refresh the fixture
"""
import html
import json
import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FIXTURE = ROOT / "tests" / "fixtures" / "fincen-index.html"
MANIFEST = ROOT / "data" / "fincen" / "index.json"

INDEX_URL = "https://www.fincen.gov/resources/advisoriesbulletinsfact-sheets/advisories"
BASE = "https://www.fincen.gov"
# fincen.gov returns 403 to the bare urllib UA; present a normal browser UA.
_UA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 Signal-Watch-authoring/0.1"

# The EFE advisory is the Phase-7 anchor; guarantee it survives even if the live
# listing markup shifts. Its detail page (acquire_fincen.py holds the direct-PDF override).
_EFE_ID = "fin-2022-a002"
_EFE_FALLBACK = {
    "id": _EFE_ID,
    "title": "FinCEN Advisory on Elder Financial Exploitation",
    "date": "2022-06-15",
    "type": "advisory",
    "url": f"{BASE}/resources/advisories/fincen-advisory-{_EFE_ID}",
}

_ROW_RE = re.compile(r"<tr>(.*?)</tr>", re.S)
_LINK_RE = re.compile(r'href="(/resources/advisories/fincen-advisory-(fin-\d{4}-a\d{3}))"')
_TIME_RE = re.compile(r'<time[^>]*datetime="(\d{4}-\d{2}-\d{2})')
_DATE_FALLBACK_RE = re.compile(r"(\d{2})/(\d{2})/(\d{4})")
# columns are keyed by stable Drupal `headers=` attributes
_SUBJECT_TD_RE = re.compile(
    r'<td[^>]*headers="view-field-advisory-subject-table-column"[^>]*>(.*?)</td>', re.S
)


def _text(fragment: str) -> str:
    """Strip tags + unescape + collapse whitespace — pure text of an HTML cell."""
    return re.sub(r"\s+", " ", html.unescape(re.sub(r"<[^>]+>", "", fragment))).strip()


def parse_index(page_html: str) -> list[dict]:
    """PURE: FinCEN advisories listing HTML -> sorted list of manifest entries.

    Each entry: {id, title, date(ISO), type, url(detail page)}. Rows without a
    valid advisory link are skipped. Deterministic: output is sorted by id.
    """
    entries: dict[str, dict] = {}
    for row in _ROW_RE.findall(page_html):
        link = _LINK_RE.search(row)
        if not link:
            continue
        path, advisory_id = link.group(1), link.group(2)
        # prefer the descriptive subject column; fall back to the <a> link text
        subject = _SUBJECT_TD_RE.search(row)
        title = _text(subject.group(1)) if subject else _text(link.group(0))
        if not title:
            title = f"FinCEN Advisory {advisory_id.upper()}"
        tm = _TIME_RE.search(row)
        if tm:
            date = tm.group(1)
        else:
            d = _DATE_FALLBACK_RE.search(row)
            date = f"{d.group(3)}-{d.group(1)}-{d.group(2)}" if d else ""
        entries[advisory_id] = {
            "id": advisory_id,
            "title": title,
            "date": date,
            "type": "advisory",
            "url": BASE + path,
        }
    # guarantee the EFE anchor is present even if the listing markup shifts
    entries.setdefault(_EFE_ID, dict(_EFE_FALLBACK))
    return [entries[k] for k in sorted(entries)]


def fetch_index() -> str:
    """LIVE thin shell (manual authoring only): GET the advisories listing HTML."""
    req = urllib.request.Request(INDEX_URL, headers={"User-Agent": _UA})
    with urllib.request.urlopen(req, timeout=60) as resp:
        return resp.read().decode("utf-8", "replace")


def _load_fixture() -> str:
    if not FIXTURE.exists():
        sys.exit(f"missing fixture {FIXTURE} — run: python3 scripts/crawl_fincen.py --fetch")
    return FIXTURE.read_text(encoding="utf-8")


def selftest() -> int:
    entries = parse_index(_load_fixture())
    keys = {"id", "title", "date", "type", "url"}
    bad = [e for e in entries if set(e) != keys or not e["id"] or not e["url"]
           or not re.fullmatch(r"\d{4}-\d{2}-\d{2}", e["date"] or "")]
    ok = len(entries) >= 3 and not bad and any(e["id"] == _EFE_ID for e in entries)
    print(f"parsed {len(entries)} entries; malformed={len(bad)}; "
          f"EFE present={any(e['id'] == _EFE_ID for e in entries)}")
    if not ok:
        print("SELFTEST FAIL", file=sys.stderr)
        return 1
    print("SELFTEST PASS")
    return 0


def write_manifest() -> int:
    entries = parse_index(_load_fixture())
    MANIFEST.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST.write_text(json.dumps(entries, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {MANIFEST} ({len(entries)} advisories)")
    return 0


def main(argv):
    if not argv or argv[0] in ("-h", "--help"):
        print(__doc__)
        return 0
    cmd = argv[0]
    if cmd == "--selftest":
        return selftest()
    if cmd == "--write":
        return write_manifest()
    if cmd == "--list":
        for e in parse_index(_load_fixture()):
            print(f"{e['id']}\t{e['date']}\t{e['title']}")
        return 0
    if cmd == "--fetch":
        FIXTURE.parent.mkdir(parents=True, exist_ok=True)
        html_text = fetch_index()
        prov = (
            "<!-- fixture: FinCEN advisories listing, saved for the crawl_fincen.py parser test (Phase 10) -->\n"
            f"<!-- source: {INDEX_URL} -->\n"
            "<!-- acquired via crawl_fincen.py --fetch (urllib, browser UA); server-rendered; do not hand-edit -->\n"
        )
        FIXTURE.write_text(prov + html_text, encoding="utf-8")
        print(f"refreshed {FIXTURE} ({len(html_text):,} chars) from {INDEX_URL}")
        return 0
    sys.exit(f"unknown option '{cmd}'. See --help.")


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
