#!/usr/bin/env python3
"""Discover the FinCEN advisory corpus into a manifest — AUTHORING-TIME ONLY.

Part of the Signal Watch ingestion pipeline (Phase 10 — SCALE). This widens the
hand-maintained 1-entry REGISTRY in acquire_fincen.py into a generated manifest of
the whole FinCEN advisories listing:

    crawl_fincen.py    → data/fincen/index.json   (manifest: {id,title,date,type,url})
    acquire_fincen.py  → data/fincen/raw/<id>.pdf (reads the manifest; resolves the PDF)
    pdf_to_md.py       → data/fincen/<id>.md      (verbatim source of truth)
    (hand-derive)      → config/typologies/<typology>.json
    build.py           → dist/<typology>/index.html

NON-NEGOTIABLE: nothing here ever runs in the ship artifact. The engine never
imports this; build.py stays stdlib-only and never fetches. This is a developer tool.

DETERMINISM SPLIT (so the committed manifest is reproducible without a live crawl):
  - parse_index(html) is a PURE function (HTML -> entries, no I/O). It is verified
    offline by `--selftest` against tests/fixtures/fincen-index.html, in the same
    runnable-stdlib-check spirit as build.py --check.
  - fetch_index() is a thin live shell (stdlib urllib, browser UA) used by `--fetch`
    to REFRESH the fixture. It is a manual authoring run, never in smoke/CI.
The committed data/fincen/index.json is generated by `--write` from the SAVED FIXTURE,
so it is reproducible offline.

The listing yields advisory DETAIL-PAGE urls (FinCEN PDF filenames are unpredictable);
resolving the actual PDF is an acquire-time hop (see acquire_fincen.py). FinCEN
advisories are U.S. federal works in the public domain (17 U.S.C. 105).

Phase 20 — multi-source: pass `--alerts` with any command to target the FinCEN ALERTS hub instead
(parse_alerts -> data/fincen-alerts/index.json; the rows link the alert PDF directly, so the manifest
url is the .pdf and acquire_fincen.py downloads it zero-hop). The advisory path is unchanged.

Usage:
    python3 scripts/crawl_fincen.py --selftest             # offline: parse the fixture + assert
    python3 scripts/crawl_fincen.py --write                # offline: fixture -> data/fincen/index.json
    python3 scripts/crawl_fincen.py --list                 # offline: print parsed entries
    python3 scripts/crawl_fincen.py --fetch                # LIVE (manual authoring): refresh the fixture
    python3 scripts/crawl_fincen.py --alerts --fetch       # LIVE: refresh the alerts hub fixture
    python3 scripts/crawl_fincen.py --alerts --write       # offline: -> data/fincen-alerts/index.json
"""
import html
import json
import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FIXTURE = ROOT / "tests" / "fixtures" / "fincen-index.html"
MANIFEST = ROOT / "data" / "fincen" / "index.json"

INDEX_URL = "https://www.fincen.gov/resources/advisoriesbulletinsfact-sheets/advisories"
BASE = "https://www.fincen.gov"
# fincen.gov returns 403 to the bare urllib UA; present a normal browser UA.
_UA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 Signal-Watch-authoring/0.1"

# Phase 20 — FinCEN ALERTS as a second source. The alerts are listed on the advisories/bulletins/
# fact-sheets HUB as rows that link the alert PDF DIRECTLY (/system/files/...Alert....pdf) with a
# canonical "FIN-YYYY-AlertNNN" id + date + title in the row — the same Drupal table shape as the
# advisories listing, so parse_alerts mirrors parse_index. Pass `--alerts` with any command below.
ALERTS_URL = "https://www.fincen.gov/resources/advisoriesbulletinsfact-sheets"
ALERTS_FIXTURE = ROOT / "tests" / "fixtures" / "fincen-alerts.html"
ALERTS_MANIFEST = ROOT / "data" / "fincen-alerts" / "index.json"
_ALERT_ID_RE = re.compile(r"\b(FIN-\d{4}-Alert\d{3})\b", re.I)

# The EFE advisory is the Phase-7 anchor; guarantee it survives even if the live
# listing markup shifts. Its detail page (acquire_fincen.py holds the direct-PDF override).
_EFE_ID = "fin-2022-a002"
_EFE_FALLBACK = {
    "id": _EFE_ID,
    "title": "FinCEN Advisory on Elder Financial Exploitation",
    "date": "2022-06-15",
    "type": "advisory",
    "url": f"{BASE}/resources/advisories/fincen-advisory-{_EFE_ID}",
}

_ROW_RE = re.compile(r"<tr>(.*?)</tr>", re.S)
_LINK_RE = re.compile(r'href="(/resources/advisories/fincen-advisory-(fin-\d{4}-a\d{3}))"')
_TIME_RE = re.compile(r'<time[^>]*datetime="(\d{4}-\d{2}-\d{2})')
_DATE_FALLBACK_RE = re.compile(r"(\d{2})/(\d{2})/(\d{4})")
# columns are keyed by stable Drupal `headers=` attributes
_SUBJECT_TD_RE = re.compile(
    r'<td[^>]*headers="view-field-advisory-subject-table-column"[^>]*>(.*?)</td>', re.S
)


def _text(fragment: str) -> str:
    """Strip tags + unescape + collapse whitespace — pure text of an HTML cell."""
    return re.sub(r"\s+", " ", html.unescape(re.sub(r"<[^>]+>", "", fragment))).strip()


def parse_index(page_html: str) -> list[dict]:
    """PURE: FinCEN advisories listing HTML -> sorted list of manifest entries.

    Each entry: {id, title, date(ISO), type, url(detail page)}. Rows without a
    valid advisory link are skipped. Deterministic: output is sorted by id.
    """
    entries: dict[str, dict] = {}
    for row in _ROW_RE.findall(page_html):
        link = _LINK_RE.search(row)
        if not link:
            continue
        path, advisory_id = link.group(1), link.group(2)
        # prefer the descriptive subject column; fall back to the <a> link text
        subject = _SUBJECT_TD_RE.search(row)
        title = _text(subject.group(1)) if subject else _text(link.group(0))
        if not title:
            title = f"FinCEN Advisory {advisory_id.upper()}"
        tm = _TIME_RE.search(row)
        if tm:
            date = tm.group(1)
        else:
            d = _DATE_FALLBACK_RE.search(row)
            date = f"{d.group(3)}-{d.group(1)}-{d.group(2)}" if d else ""
        entries[advisory_id] = {
            "id": advisory_id,
            "title": title,
            "date": date,
            "type": "advisory",
            "url": BASE + path,
        }
    # guarantee the EFE anchor is present even if the listing markup shifts
    entries.setdefault(_EFE_ID, dict(_EFE_FALLBACK))
    return [entries[k] for k in sorted(entries)]


def parse_alerts(page_html: str) -> list[dict]:
    """PURE: FinCEN alerts hub HTML -> sorted list of manifest entries (Phase 20).

    Each alerts-table row is three <td> cells: [0] <a href="<direct .pdf>">FIN-YYYY-AlertNNN</a>,
    [1] the date, [2] the title. We take the canonical id from the cell-0 link text and the PDF
    DIRECTLY from its href (acquire_fincen.py downloads it zero-hop). Skips Spanish translations
    + rescinded (withdrawn) PDFs — each Spanish alert also has an English row — and dedups by id.
    Deterministic: output sorted by id.
    """
    entries: dict[str, dict] = {}
    for row in _ROW_RE.findall(page_html):
        cells = re.findall(r"<td[^>]*>(.*?)</td>", row, re.S)
        if len(cells) < 3:
            continue
        a = re.search(r'<a[^>]*href="([^"]+\.pdf)"[^>]*>(.*?)</a>', cells[0], re.I | re.S)
        if not a:
            continue
        href, link_text = a.group(1), _text(a.group(2))
        low = href.lower()
        if "alert" not in low:
            continue                          # not a FinCEN Alert row
        if "spanish" in low or "rescinded" in low:
            continue                          # skip translations + withdrawn guidance
        mid = _ALERT_ID_RE.search(link_text)
        if mid:
            alert_id = mid.group(1).lower()                  # canonical FIN-YYYY-AlertNNN
        else:                                                # fall back to a filename slug
            stem = re.sub(r"\.pdf$", "", href.rsplit("/", 1)[-1], flags=re.I)
            alert_id = "fincen-alert-" + re.sub(r"[^a-z0-9]+", "-", stem.lower()).strip("-")
        title = _text(cells[2]) or f"FinCEN Alert {alert_id.upper()}"
        tm = _TIME_RE.search(cells[1])
        if tm:
            date = tm.group(1)
        else:
            d = _DATE_FALLBACK_RE.search(cells[1])
            date = f"{d.group(3)}-{d.group(1)}-{d.group(2)}" if d else ""
        url = href if href.startswith("http") else BASE + href
        entries[alert_id] = {
            "id": alert_id,
            "title": title,
            "date": date,
            "type": "alert",
            # direct .pdf (acquire downloads zero-hop). Some FinCEN filenames contain literal
            # spaces in the href — encode them so the manifest holds a fetchable URL (URLs that
            # already use %20 are left as-is, so no double-encoding).
            "url": url.replace(" ", "%20"),
        }
    return [entries[k] for k in sorted(entries)]


def fetch_index(url: str = INDEX_URL) -> str:
    """LIVE thin shell (manual authoring only): GET a listing/hub HTML."""
    req = urllib.request.Request(url, headers={"User-Agent": _UA})
    with urllib.request.urlopen(req, timeout=60) as resp:
        return resp.read().decode("utf-8", "replace")


def _load_fixture(fixture: Path = FIXTURE) -> str:
    if not fixture.exists():
        sys.exit(f"missing fixture {fixture} — run a `--fetch` (e.g. crawl_fincen.py --fetch)")
    return fixture.read_text(encoding="utf-8")


def selftest(parse=parse_index, fixture: Path = FIXTURE, anchor: str = _EFE_ID) -> int:
    entries = parse(_load_fixture(fixture))
    keys = {"id", "title", "date", "type", "url"}
    bad = [e for e in entries if set(e) != keys or not e["id"] or not e["url"]
           or not re.fullmatch(r"\d{4}-\d{2}-\d{2}", e["date"] or "")]
    has_anchor = anchor is None or any(e["id"] == anchor for e in entries)
    ok = len(entries) >= 3 and not bad and has_anchor
    print(f"parsed {len(entries)} entries; malformed={len(bad)}"
          + (f"; {anchor} present={any(e['id'] == anchor for e in entries)}" if anchor else ""))
    if not ok:
        print("SELFTEST FAIL", file=sys.stderr)
        return 1
    print("SELFTEST PASS")
    return 0


def write_manifest(parse=parse_index, fixture: Path = FIXTURE,
                   manifest: Path = MANIFEST, noun: str = "advisories") -> int:
    entries = parse(_load_fixture(fixture))
    manifest.parent.mkdir(parents=True, exist_ok=True)
    manifest.write_text(json.dumps(entries, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {manifest} ({len(entries)} {noun})")
    return 0


def _fetch_fixture(url: str, fixture: Path, label: str) -> int:
    fixture.parent.mkdir(parents=True, exist_ok=True)
    html_text = fetch_index(url)
    prov = (
        f"<!-- fixture: FinCEN {label}, saved for the crawl_fincen.py parser test -->\n"
        f"<!-- source: {url} -->\n"
        "<!-- acquired via crawl_fincen.py --fetch (urllib, browser UA); server-rendered; do not hand-edit -->\n"
    )
    fixture.write_text(prov + html_text, encoding="utf-8")
    print(f"refreshed {fixture} ({len(html_text):,} chars) from {url}")
    return 0


def main(argv):
    if not argv or "-h" in argv or "--help" in argv:
        print(__doc__)
        return 0
    # Phase 20: `--alerts` switches every command to the FinCEN alerts source (hub + parse_alerts).
    alerts = "--alerts" in argv
    rest = [a for a in argv if a != "--alerts"]
    if not rest:
        print(__doc__)
        return 0
    cmd = rest[0]
    parse = parse_alerts if alerts else parse_index
    fixture = ALERTS_FIXTURE if alerts else FIXTURE
    manifest = ALERTS_MANIFEST if alerts else MANIFEST
    url = ALERTS_URL if alerts else INDEX_URL
    anchor = None if alerts else _EFE_ID
    noun = "alerts" if alerts else "advisories"
    label = "alerts hub" if alerts else "advisories listing"
    if cmd == "--selftest":
        return selftest(parse, fixture, anchor)
    if cmd == "--write":
        return write_manifest(parse, fixture, manifest, noun)
    if cmd == "--list":
        for e in parse(_load_fixture(fixture)):
            print(f"{e['id']}\t{e['date']}\t{e['title']}")
        return 0
    if cmd == "--fetch":
        return _fetch_fixture(url, fixture, label)
    sys.exit(f"unknown option '{cmd}'. See --help.")


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
